#!/usr/bin/python

import pty
print """
  _____     _______  ________  
 |_   _|   |_   __ \|_   __  | 
   | |       | |__) | | |_ \_| 
   | |   _   |  ___/  |  _| _  
  _| |__/ | _| |_    _| |__/ | 
 |________||_____|  |________| 
                               
                    by hrdn
"""
if raw_input("Password: ") == "quickfox64":
    pty.spawn("/bin/bash")
else:
    print("EXITED")
